import { describe, it, expect, vi, beforeEach } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import PlaylistForm from './PlaylistForm'
import * as apiModule from '@/lib/api'
import { ethereumAddressToDIDPKH } from '@/lib/signing'

const TEST_WALLET = '0x000000000000000000000000000000000000aBcD'
const TEST_WALLET_DID = ethereumAddressToDIDPKH(TEST_WALLET)

// wagmi: stable address + minimal wallet client (signing is mocked separately).
vi.mock('wagmi', () => {
  const address = '0x000000000000000000000000000000000000aBcD'
  return {
    useAccount: () => ({ address }),
    useWalletClient: () => ({ data: { account: { address } } }),
  }
})

// signDocument mock uses the live ethereumAddressToDIDPKH for kid so it
// matches what the form computes; declared at module scope so the mock
// factory can close over it.
const signKid = ethereumAddressToDIDPKH('0x000000000000000000000000000000000000aBcD')

// Toast: capture title/description so error-path assertions can read them.
const toastMock = vi.fn()
vi.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: toastMock }),
}))

// signing: bypass viem and return a deterministic signature object.
vi.mock('@/lib/signing', async () => {
  const actual = await vi.importActual<typeof import('@/lib/signing')>(
    '@/lib/signing',
  )
  return {
    ...actual,
    signDocument: vi.fn(async (_raw, _wc, role: 'curator' | 'publisher') => ({
      alg: 'eip191',
      kid: signKid,
      ts: new Date().toISOString(),
      payload_hash: 'sha256:test',
      role,
      sig: 'test-signature',
    })),
  }
})

// api: keep helpers + FeedAPIError real (used by friendlyPublishError, URLs);
// stub the network calls (publish/getPlaylist/patchPlaylist).
vi.mock('@/lib/api', async () => {
  const actual = await vi.importActual<typeof apiModule>('@/lib/api')
  return {
    ...actual,
    publishPlaylist: vi.fn(),
    getPlaylist: vi.fn(),
    patchPlaylist: vi.fn(),
  }
})

const mockedApi = apiModule as typeof apiModule & {
  publishPlaylist: ReturnType<typeof vi.fn>
  getPlaylist: ReturnType<typeof vi.fn>
  patchPlaylist: ReturnType<typeof vi.fn>
}

function fillFormAndPublish(title: string, source: string) {
  fireEvent.change(screen.getByLabelText(/Title \*/i), {
    target: { value: title },
  })
  fireEvent.change(screen.getByLabelText(/Source URI \*/i), {
    target: { value: source },
  })
  fireEvent.click(screen.getByRole('button', { name: /Sign & publish/i }))
}

describe('PlaylistForm — publish flow', () => {
  beforeEach(() => {
    localStorage.clear()
    toastMock.mockClear()
    mockedApi.publishPlaylist.mockReset()
    mockedApi.getPlaylist.mockReset()
    mockedApi.patchPlaylist.mockReset()
  })

  it('regenerates id after a successful create, so "Publish another" POSTs a fresh document', async () => {
    // Preflight: 404 means the id is not yet on the feed → POST path.
    mockedApi.getPlaylist.mockRejectedValue(new apiModule.FeedAPIError('not found', 404))
    mockedApi.publishPlaylist.mockImplementation(async (p) => ({
      ...(p as Record<string, unknown>),
      slug: 'first-slug',
    }))

    render(<PlaylistForm extensionsEnabled={false} />)
    fillFormAndPublish('First playlist', 'https://example.com/a.mp4')

    await waitFor(() => {
      expect(mockedApi.publishPlaylist).toHaveBeenCalledTimes(1)
    })
    const firstCallBody = mockedApi.publishPlaylist.mock.calls[0][0] as { id: string }
    const firstId = firstCallBody.id
    expect(typeof firstId).toBe('string')
    expect(firstId.length).toBeGreaterThan(0)

    // The post-publish panel should be visible — click "Publish another" to
    // return to a clean form (id must be regenerated by the reset code path).
    const publishAnother = await screen.findByRole('button', {
      name: /Publish another/i,
    })
    fireEvent.click(publishAnother)

    // Fill in different content; the id is internal state, so the only way to
    // observe it is via the next publishPlaylist call payload.
    fillFormAndPublish('Second playlist', 'https://example.com/b.mp4')

    await waitFor(() => {
      expect(mockedApi.publishPlaylist).toHaveBeenCalledTimes(2)
    })
    const secondCallBody = mockedApi.publishPlaylist.mock.calls[1][0] as { id: string }
    const secondId = secondCallBody.id
    expect(secondId).not.toBe(firstId)

    // And critically — patchPlaylist must NOT have been used. If id had
    // been reused, preflight would have found the prior doc (mocked above
    // with .mockRejectedValue 404) and we'd still POST, BUT in the real
    // wild the prior id would resolve and silently overwrite. The
    // not-equal id assertion above is the load-bearing check; this just
    // documents that the create path stays a POST.
    expect(mockedApi.patchPlaylist).not.toHaveBeenCalled()
  })

  it('refuses to sign or PATCH when preflight returns a doc signed by a different wallet', async () => {
    // Existing doc was signed by ANOTHER wallet (not the connected one).
    // The ownership gate must abort before signing or PATCHing.
    mockedApi.getPlaylist.mockResolvedValue({
      dpVersion: '1.1.0',
      id: 'preexisting-id',
      slug: 'preexisting',
      title: 'Preexisting',
      created: '2025-01-01T00:00:00Z',
      items: [],
      signatures: [
        {
          alg: 'eip191',
          kid: 'did:pkh:eip155:1:0xDeAd000000000000000000000000000000000001',
          ts: '2025-01-01T00:00:00Z',
          payload_hash: 'sha256:other',
          role: 'curator',
          sig: 'other-sig',
        },
      ],
    })

    const signingModule = await import('@/lib/signing')
    const signSpy = signingModule.signDocument as unknown as ReturnType<typeof vi.fn>
    signSpy.mockClear()

    render(<PlaylistForm extensionsEnabled={false} />)
    fillFormAndPublish('Whatever', 'https://example.com/a.mp4')

    // Wait for the gate's update-failed toast.
    await waitFor(() => {
      const updateFailures = toastMock.mock.calls.filter(
        ([arg]) => arg?.title === 'Update failed',
      )
      expect(updateFailures.length).toBeGreaterThan(0)
    })

    // Critically: neither signing nor the PATCH endpoint may have been called.
    expect(signSpy).not.toHaveBeenCalled()
    expect(mockedApi.patchPlaylist).not.toHaveBeenCalled()
    expect(mockedApi.publishPlaylist).not.toHaveBeenCalled()
  })

  it('shows the overwrite-specific error when an auto-overwrite PATCH is rejected (wrong wallet)', async () => {
    // Preflight resolves: id already on the feed → form will route to PATCH.
    // Existing doc was previously signed by THIS wallet (so the client-side
    // ownership gate passes and we reach the PATCH); the server then rejects
    // the PATCH with 401 — the case we're testing.
    mockedApi.getPlaylist.mockResolvedValue({
      dpVersion: '1.1.0',
      id: 'preexisting-id',
      slug: 'preexisting',
      title: 'Preexisting',
      created: '2025-01-01T00:00:00Z',
      items: [],
      signatures: [
        {
          alg: 'eip191',
          kid: TEST_WALLET_DID,
          ts: '2025-01-01T00:00:00Z',
          payload_hash: 'sha256:prior',
          role: 'curator',
          sig: 'prior-sig',
        },
      ],
    })
    // PATCH rejected as wrong wallet (401).
    mockedApi.patchPlaylist.mockRejectedValue(
      new apiModule.FeedAPIError('signature rejected', 401, 'unauthorized'),
    )

    render(<PlaylistForm extensionsEnabled={false} />)
    fillFormAndPublish('Whatever', 'https://example.com/a.mp4')

    await waitFor(() => {
      expect(mockedApi.patchPlaylist).toHaveBeenCalledTimes(1)
    })

    // The catch must classify this as an update failure → the toast
    // description must contain the overwrite-specific copy, not the
    // create-mode "wallet matches curator" message.
    await waitFor(() => {
      const updateFailureCalls = toastMock.mock.calls.filter(
        ([arg]) => arg?.title === 'Update failed',
      )
      expect(updateFailureCalls.length).toBeGreaterThan(0)
      const desc = updateFailureCalls[updateFailureCalls.length - 1][0]
        .description as string
      expect(desc).toMatch(/different wallet/i)
    })
  })

  // playlists-extension §3.6. A playlist carrying an inline Ref Manifest is
  // authored elsewhere (ff-cli, an agent) and pasted into the JSON tab — there
  // is no form control for the field — so the JSON tab is the whole user-facing
  // path for it, and these two cases are what "publishing an item with an
  // inline manifest works" actually means end to end.
  function pasteJsonAndPublish(document: unknown) {
    // Radix tabs switch on mousedown, not click.
    fireEvent.mouseDown(screen.getByRole('tab', { name: /JSON/i }))
    fireEvent.change(screen.getByPlaceholderText(/paste DP-1 JSON/i), {
      target: { value: JSON.stringify(document) },
    })
    fireEvent.click(screen.getByRole('button', { name: /Sign & publish/i }))
  }

  const INLINE_MANIFEST = {
    refVersion: '0.1.0',
    id: 'ref-9d26ecb3',
    created: '2026-07-28T00:00:00Z',
    locale: 'en',
    metadata: {
      title: 'Pre-Process',
      artists: [{ name: 'Casey Reas', id: '' }],
    },
  }

  it('publishes a pasted item inlineManifest verbatim (JSON tab, extensions on)', async () => {
    mockedApi.getPlaylist.mockRejectedValue(new apiModule.FeedAPIError('not found', 404))
    mockedApi.publishPlaylist.mockImplementation(async (p) => p as Record<string, unknown>)

    render(<PlaylistForm extensionsEnabled />)
    pasteJsonAndPublish({
      dpVersion: '1.1.0',
      title: 'Inline manifest playlist',
      items: [
        {
          source: 'https://example.com/art/pre-process.html',
          inlineManifest: INLINE_MANIFEST,
        },
      ],
    })

    await waitFor(() => {
      expect(mockedApi.publishPlaylist).toHaveBeenCalledTimes(1)
    })
    const body = mockedApi.publishPlaylist.mock.calls[0][0] as {
      items: Array<Record<string, unknown>>
    }
    // Deep equality, not a spot check: the artist `"id": ""` is the field a
    // typed re-marshal would drop, and dropping it changes the signed bytes.
    expect(body.items[0].inlineManifest).toEqual(INLINE_MANIFEST)
  })

  it('refuses to publish an inlineManifest missing its envelope', async () => {
    mockedApi.getPlaylist.mockRejectedValue(new apiModule.FeedAPIError('not found', 404))

    render(<PlaylistForm extensionsEnabled />)
    pasteJsonAndPublish({
      dpVersion: '1.1.0',
      title: 'Broken manifest playlist',
      items: [
        {
          source: 'https://example.com/art/pre-process.html',
          inlineManifest: { refVersion: '0.1.0', id: 'ref-9d26ecb3' },
        },
      ],
    })

    await waitFor(() => {
      expect(
        toastMock.mock.calls.some(([arg]) =>
          /inlineManifest/.test(String(arg?.description ?? '')),
        ),
      ).toBe(true)
    })
    expect(mockedApi.publishPlaylist).not.toHaveBeenCalled()
  })
})
