import { describe, it, expect, vi, beforeEach } from 'vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import PlaylistForm from './PlaylistForm'
import * as apiModule from '@/lib/api'

// wagmi: stable address + minimal wallet client (signing is mocked separately).
vi.mock('wagmi', () => {
  const address = '0x000000000000000000000000000000000000aBcD'
  return {
    useAccount: () => ({ address }),
    useWalletClient: () => ({ data: { account: { address } } }),
  }
})

// Toast: capture title/description so error-path assertions can read them.
const toastMock = vi.fn()
vi.mock('@/hooks/use-toast', () => ({
  useToast: () => ({ toast: toastMock }),
}))

// signing: bypass viem and return a deterministic signature object.
vi.mock('@/lib/signing', async () => {
  const actual = await vi.importActual<typeof import('@/lib/signing')>(
    '@/lib/signing',
  )
  return {
    ...actual,
    signDocument: vi.fn(async (_raw, _wc, role: 'curator' | 'publisher') => ({
      alg: 'eip191',
      kid: 'did:pkh:eip155:1:0x000000000000000000000000000000000000aBcD',
      ts: new Date().toISOString(),
      payload_hash: 'sha256:test',
      role,
      sig: 'test-signature',
    })),
  }
})

// api: keep helpers + FeedAPIError real (used by friendlyPublishError, URLs);
// stub the network calls (publish/getPlaylist/patchPlaylist).
vi.mock('@/lib/api', async () => {
  const actual = await vi.importActual<typeof apiModule>('@/lib/api')
  return {
    ...actual,
    publishPlaylist: vi.fn(),
    getPlaylist: vi.fn(),
    patchPlaylist: vi.fn(),
  }
})

const mockedApi = apiModule as typeof apiModule & {
  publishPlaylist: ReturnType<typeof vi.fn>
  getPlaylist: ReturnType<typeof vi.fn>
  patchPlaylist: ReturnType<typeof vi.fn>
}

function fillFormAndPublish(title: string, source: string) {
  fireEvent.change(screen.getByLabelText(/Title \*/i), {
    target: { value: title },
  })
  fireEvent.change(screen.getByLabelText(/Source URI \*/i), {
    target: { value: source },
  })
  fireEvent.click(screen.getByRole('button', { name: /Sign & publish/i }))
}

describe('PlaylistForm — publish flow', () => {
  beforeEach(() => {
    localStorage.clear()
    toastMock.mockClear()
    mockedApi.publishPlaylist.mockReset()
    mockedApi.getPlaylist.mockReset()
    mockedApi.patchPlaylist.mockReset()
  })

  it('regenerates id after a successful create, so "Publish another" POSTs a fresh document', async () => {
    // Preflight: 404 means the id is not yet on the feed → POST path.
    mockedApi.getPlaylist.mockRejectedValue(new apiModule.FeedAPIError('not found', 404))
    mockedApi.publishPlaylist.mockImplementation(async (p) => ({
      ...(p as Record<string, unknown>),
      slug: 'first-slug',
    }))

    render(<PlaylistForm extensionsEnabled={false} />)
    fillFormAndPublish('First playlist', 'https://example.com/a.mp4')

    await waitFor(() => {
      expect(mockedApi.publishPlaylist).toHaveBeenCalledTimes(1)
    })
    const firstCallBody = mockedApi.publishPlaylist.mock.calls[0][0] as { id: string }
    const firstId = firstCallBody.id
    expect(typeof firstId).toBe('string')
    expect(firstId.length).toBeGreaterThan(0)

    // The post-publish panel should be visible — click "Publish another" to
    // return to a clean form (id must be regenerated by the reset code path).
    const publishAnother = await screen.findByRole('button', {
      name: /Publish another/i,
    })
    fireEvent.click(publishAnother)

    // Fill in different content; the id is internal state, so the only way to
    // observe it is via the next publishPlaylist call payload.
    fillFormAndPublish('Second playlist', 'https://example.com/b.mp4')

    await waitFor(() => {
      expect(mockedApi.publishPlaylist).toHaveBeenCalledTimes(2)
    })
    const secondCallBody = mockedApi.publishPlaylist.mock.calls[1][0] as { id: string }
    const secondId = secondCallBody.id
    expect(secondId).not.toBe(firstId)

    // And critically — patchPlaylist must NOT have been used. If id had
    // been reused, preflight would have found the prior doc (mocked above
    // with .mockRejectedValue 404) and we'd still POST, BUT in the real
    // wild the prior id would resolve and silently overwrite. The
    // not-equal id assertion above is the load-bearing check; this just
    // documents that the create path stays a POST.
    expect(mockedApi.patchPlaylist).not.toHaveBeenCalled()
  })

  it('shows the overwrite-specific error when an auto-overwrite PATCH is rejected (wrong wallet)', async () => {
    // Preflight resolves: id already on the feed → form will route to PATCH.
    mockedApi.getPlaylist.mockResolvedValue({
      dpVersion: '1.1.0',
      id: 'preexisting-id',
      slug: 'preexisting',
      title: 'Preexisting',
      created: '2025-01-01T00:00:00Z',
      items: [],
    })
    // PATCH rejected as wrong wallet (401).
    mockedApi.patchPlaylist.mockRejectedValue(
      new apiModule.FeedAPIError('signature rejected', 401, 'unauthorized'),
    )

    render(<PlaylistForm extensionsEnabled={false} />)
    fillFormAndPublish('Whatever', 'https://example.com/a.mp4')

    await waitFor(() => {
      expect(mockedApi.patchPlaylist).toHaveBeenCalledTimes(1)
    })

    // The catch must classify this as an update failure → the toast
    // description must contain the overwrite-specific copy, not the
    // create-mode "wallet matches curator" message.
    await waitFor(() => {
      const updateFailureCalls = toastMock.mock.calls.filter(
        ([arg]) => arg?.title === 'Update failed',
      )
      expect(updateFailureCalls.length).toBeGreaterThan(0)
      const desc = updateFailureCalls[updateFailureCalls.length - 1][0]
        .description as string
      expect(desc).toMatch(/different wallet/i)
    })
  })
})
